app.run(function($rootScope){$rootScope._=_;});app.factory('Posts',function(config,$http,$location){return{get_posts:function(stateParams){var s=stateParams.s||''
var page=stateParams.page||1
return $http.get(config.blog_api_url+'wp-json/blog/posts?page='+page+'&per_page='+config.per_page+'&s='+s).then(function(response){return response;});},get_post:function(slug){if(slug==undefined)return false;return $http.get(config.blog_api_url+'wp-json/blog/posts/'+slug).then(function(response){if(response.data=='null'){$location.path('/somewhereElse');}return response.data;});},get_recent_posts:function(){return $http.get(config.blog_api_url+'wp-json/blog/posts?per_page='+5).then(function(response){return response.data;});},GetPager:function(totalPages,currentPage){currentPage=parseInt((currentPage||1));totalPages=parseInt(totalPages);var startPage,endPage;if(totalPages==2){startPage=1;endPage=2;}else if(totalPages==3){startPage=1;endPage=3;}else if(currentPage==1){startPage=1;endPage=4;}else if(currentPage<=2){startPage=1;endPage=4;}else if(currentPage+2>=totalPages){startPage=totalPages-3;endPage=totalPages;}else{startPage=currentPage-1;endPage=currentPage+2;}var pages=_.range(startPage,endPage+1);return{currentPage:parseInt(currentPage),totalPages:parseInt(totalPages),startPage:parseInt(startPage),endPage:parseInt(endPage),pages:pages};}}});app.controller("EmailCtrl",['$scope','$timeout','$http','$rootScope','config','$state',function($scope,$timeout,$http,$rootScope,config,$state){$scope.contact={};  $scope.newcontact = {};$scope.career={};$scope.register={};$rootScope.is_loading=false;$scope.contact_us=function(is_valid){if(!is_valid)return false;$rootScope.is_loading=true;$http.post(config.api_url+'email.php',$scope.contact).then(function(response){if(response.data.status=="success"){console.log(response.data);window.location.href='/thanks-page.html';}$scope.response=response.data;$scope.element_hide=true;$timeout(function(){$scope.element_hide=false;},10000);$rootScope.is_loading=false;$scope.contact={};});}

  $scope.newcontact_us = function(is_valid){
  	if(!is_valid) return false;
  	  $rootScope.is_loading = true;
  	  $http.post(config.api_url+'newemailpop.php', $scope.newcontact).then(function(response){
        if(response.data.status == "success")
        {
	  console.log(response.data);
          window.location.href  = '/thanks-page.html';

          //$state.go('thanks')
        }
    		$scope.response = response.data;
        $scope.element_hide = true;
        $timeout(function() {
          $scope.element_hide = false;
        }, 10000);
    		$rootScope.is_loading = false;
    		$scope.newcontact = {};
    	});
  }
$scope.career_hire=function(is_valid){if(!is_valid)return false;fd=new FormData();angular.forEach($scope.career,function(val,key){if(key=='file_upload'){angular.forEach(val,function(file){fd.append('file_upload',file);});}else{fd.append(key,val);}});$rootScope.is_loading=true;$http.post(config.api_url+'career.php',fd,{transformRequest:angular.identity,headers:{'Content-Type':undefined}}).then(function(response){if(response.data.status=="success"){window.location.href='/thanks-page.html';}$scope.response=response.data;$scope.element_hide=true;$timeout(function(){$scope.element_hide=false;},10000);$rootScope.is_loading=false;$scope.career={};});}
$scope.register_now=function(is_valid){if(!is_valid)return false;$rootScope.is_loading=true;$http.post(config.api_url+'registernow.php',$scope.register).then(function(response){if(response.data.status=="success"){$('#register-now').modal('hide');window.location.href='/thanks-page.html';}$scope.response=response.data;$scope.element_hide=true;$timeout(function(){$scope.element_hide=false;},10000);$rootScope.is_loading=false;$scope.register={};});}}]);app.controller("PostsCtrl",['$stateParams','$scope','$state','$http','$rootScope','Posts','$posts','$recent_posts',function($stateParams,$scope,$state,$http,$rootScope,Posts,$posts,$recent_posts){$scope.search={};if($posts!=undefined){$scope.posts=$posts.posts;$scope.pages=$posts;}remainder=0
if(($scope.pages.total%3)!=0){remainder=1}totalPages=($scope.pages.total/3)+remainder;$scope.pager=Posts.GetPager(totalPages,$stateParams.page);$scope.recent_posts=$recent_posts.posts;$scope.setPage=function(page){$state.go('blog',{page:page},{reload:true});};$scope.search_post=function(){$stateParams.s=$scope.search.textField;$stateParams.page=1;$state.go('blog',$stateParams,{reload:true});};}]);app.controller("SinglePostCtrl",['config','$stateParams','$scope','$state','$http','$rootScope','Posts','$post','$recent_posts',function(config,$stateParams,$scope,$state,$http,$rootScope,Posts,$post,$recent_posts){$scope.search={};$scope.comments=[];$scope.comment_data={};if($post!=undefined){$rootScope.MetaTags=$post.post_meta;if($post.post_meta.title==""){$rootScope.MetaTags.title=$post.post_title;}$scope.post=$post;$http.get(config.blog_api_url+'wp-json/wp/v2/comments?post='+$post.ID).then(function(response){$scope.comments=response.data;});$scope.post_comment=function(){$scope.comment_data.post=$post.ID;$rootScope.is_loading=true;$http.post(config.blog_api_url+'wp-json/wp/v2/comments/',$scope.comment_data).then(function(data,status,headers,config){$scope.response=data;$rootScope.is_loading=false;$scope.comment_data={};$state.go('blog_details',$stateParams,{reload:true});});};}$scope.recent_posts=$recent_posts.posts;$scope.search_post=function(){$stateParams.s=$scope.search.textField;$stateParams.page=1;$state.go('blog',$stateParams,{reload:true});};}]);app.controller("HomeCtrl",['$stateParams','$scope','$state','$http','$rootScope','Posts','$posts',function($stateParams,$scope,$state,$http,$rootScope,Posts,$posts){if($posts!=undefined){$scope.posts=$posts.posts;}}]);
